var ws_queue=[];var ws_queue_in_process=false;var order_book_chart=null;var channelMax=10;var audioChannels=[];for(a=0;a<channelMax;a++){audioChannels[a]=[];audioChannels[a]['channel']=new Audio();audioChannels[a]['finished']=-1;}
function price_format(num){var Amount=parseFloat(num);var DecimalSeparator=Number("1.2").toLocaleString().substr(1,1);var decimalPlaces=parseInt($('body').data('decimal-counter'),10);var AmountWithCommas=Amount.toLocaleString();var arParts=String(AmountWithCommas).split(DecimalSeparator);var intPart=arParts[0];var decPart=(arParts.length>1?arParts[1]:'');decPart=(decPart+Utils.repeatString('0',decimalPlaces)).substr(0,decimalPlaces||2);return intPart+DecimalSeparator+decPart;}
function play_multi_sound(audioElement){var thisTime=[];$.each(audioChannels,function(channelIndex,audioChannel){thisTime=new Date().getTime();if(audioChannels[channelIndex]['finished']<thisTime){audioChannels[channelIndex]['finished']=thisTime+document.getElementById(audioElement).duration*1000;audioChannels[channelIndex]['channel'].src=document.getElementById(audioElement).src;audioChannels[channelIndex]['channel'].load();audioChannels[channelIndex]['channel'].play();return false;}});}
function floatformat(num,places){return parseFloat(num).toFixed(places);}
function drawOrderBookChart(months,productionByCountry){var countries=['Bid','Ask',];var data=new google.visualization.DataTable();data.addColumn('string','Month');for(var i=0;i<countries.length;++i){data.addColumn('number',countries[i]);}
data.addRows(months.length);for(var i=0;i<months.length;++i){data.setCell(i,0,months[i]);}
for(var i=0;i<countries.length;++i){var country=productionByCountry[i];for(var month=0;month<months.length;++month){data.setCell(month,i+1,country[month]);}}
order_book_chart.draw(data,{width:960,height:350,legend:{position:'none'},chartArea:{width:"90%",height:"70%"},vAxis:{minValue:0},colors:['#8EC919','#FF2A68'],backgroundColor:'#F7F6F2'});}
function update_order_book_chart(){var bid=parseFloat($($('table#live_bid tr')[1]).attr('price')),ask=parseFloat($($('table#live_ask tr')[1]).attr('price')),decimalBase=$('body').data('decimal-base'),decimalCounter=$('body').data('decimal-counter');if(isNaN(bid)){bid=0.00;}
if(isNaN(ask)){bid=0.00;}
if(bid<ask){var spread=ask-bid;var band=10;var current_price=(bid+ask)/2
current_price=parseFloat(floatformat(current_price,decimalCounter));var min_price=parseFloat(floatformat(current_price-(current_price*(band/100)),decimalCounter));var max_price=parseFloat(floatformat(current_price+(current_price*(band/100)),decimalCounter));var prices_chart=Array();var amounts_chart=Array();amounts_chart.push(Array());amounts_chart.push(Array());var step=1/Math.pow(10,decimalCounter);for(var i=min_price;i<current_price;i=i+step){prices_chart.push(floatformat(i,decimalCounter));amounts_chart[0].push(0.00)
amounts_chart[1].push(NaN)}
var bids_num=prices_chart.length;for(var i=current_price;i<=max_price;i=i+step){prices_chart.push(floatformat(i,decimalCounter));}
var amount_sum=0.00;var price_index=bids_num;$('table#live_bid tr').each(function(i,e){if(i>0){var item=$(e);var amount=parseFloat(item.attr('amount'));var price=parseFloat(item.attr('price'));for(i2=price_index;i2>=0;i2=i2-1){price_index-=1;if(price==parseFloat(prices_chart[i2])){amount_sum+=amount;amounts_chart[0][price_index+1]=amount_sum;break;}else{amounts_chart[0][price_index+1]=amount_sum;}}}});if(price_index>0){for(i2=price_index;i2>=0;i2=i2-1){price_index-=1;amounts_chart[0][price_index+1]=amount_sum;}}
var amount_sum=0.00;var price_index=bids_num;$('table#live_ask tr').each(function(i,e){if(i>0){var item=$(e);var amount=parseFloat(item.attr('amount'));var price=parseFloat(item.attr('price'));for(i2=price_index;i2<=prices_chart.length;i2+=1){price_index+=1;if(price==parseFloat(prices_chart[i2])){amount_sum+=amount;amounts_chart[1][price_index-1]=amount_sum;break;}else{amounts_chart[1][price_index-1]=amount_sum;}}}});if(price_index<prices_chart.length){for(i2=price_index;i2<=prices_chart.length;i2+=1){price_index+=1;amounts_chart[1][price_index-1]=amount_sum;}}
drawOrderBookChart(prices_chart,amounts_chart);}}
function update_24h_volume(){var baseCurrency=$('body').data('base-currency').toLowerCase(),counterCurrency=$('body').data('counter-currency').toLowerCase(),decimalBase=$('body').data('decimal-base'),decimalCounter=$('body').data('decimal-counter');$.getJSON('api/v2/ticker/'+baseCurrency+counterCurrency+'/',function(data){volume=Math.round(data.volume,decimalBase);});}
var BaseUtils=(function(){var r={testVariable:[],initBaseUtils:function(){$('#help_trigger').click(function(){$('.help_box').slideToggle(100,'swing');});$('.row_link tr').click(function(){window.location=$(this).find('a').attr('href');}).hover(function(){$(this).toggleClass('hover');});function scrollToDiv(element,navheight){var offset=element.offset();var offsetTop=offset.top;var totalScroll=offsetTop-navheight;$('body,html').animate({scrollTop:totalScroll},300);}
$('ul.faq_list li a').click(function(){var el=$(this).attr('href');var elWrapped=$(el);scrollToDiv(elWrapped,40);return false;});$('.on_off').iphoneStyle();$('.yes_no').iphoneStyle({checkedLabel:'YES',uncheckedLabel:'NO'});var rotation=function(){$("#icon-loading").rotate({angle:0,animateTo:360,callback:rotation,easing:function(x,t,b,c,d){return c*(t/d)+b;}});};rotation();$('#collapse_trigger').click(function(){$('.main_nav').toggle();});$('#collapse_trigger_menu').click(function(){if($('#collapse_trigger_menu').hasClass('active')){$('.default_menu').hide();$(this).html('Show menu');$(this).removeClass('active');}
else{$('.default_menu').show();$(this).html('Hide menu');$(this).addClass('active');}});$('input[placeholder], textarea[placeholder]').placeholder();$('.dropdown-toggle').dropdown();$(".input").bind('focus blur',function(){$(this).toggleClass('focus')});$('.value').tooltip({selector:'.trigger-tooltip',placement:'right'});}},u={initialize:function(){r.initBaseUtils()}};return u;}());$(BaseUtils.initialize);